services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    volumes:
      - .:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
    extra_hosts:
      - "host.docker.internal:host-gateway"
    profiles: [ "web" ]
    networks:
      - laravel

  web:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    profiles: [ "web" ]
    networks:
      - laravel

  queue:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    command: /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
    volumes:
      - .:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
    extra_hosts:
      - "host.docker.internal:host-gateway"
    profiles: [ "queue" ]
    networks:
      - laravel

  scheduler:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    command: php artisan schedule:work
    volumes:
      - .:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
    extra_hosts:
      - "host.docker.internal:host-gateway"
    profiles: [ "scheduler" ]
    networks:
      - laravel

networks:
  laravel:
    external: true
    name: laravel-skeleton_laravel
